project:
  type: website

website:
  title: "Ömür Uğur, PhD"

  navbar:
    right:
      # - href: index.qmd
      #   text: Home
      - href: about.qmd
        text: About Me
      - icon: github
        # text: GitHub
        href: https://github.com/ougur-phd
        target: "_blank"

format:
  html:
    theme: 
      dark: [united, united-dark.scss]
      light: united
#    css: united-dark.css
    toc: true



